git pull origin nano-rewrite
env BOT_TOKEN=NzU5ODAzNzQzNjcwNjMyNDU5.X3C0YA.GQX5wYxzif3Gk3-SjuBARH-HvnM DEVELOPER_KEY=419826129826873345  REDDIT_CLIENT_ID=$REDDIT_CLIENT_ID REDDIT_CLIENT_SECRET=$REDDIT_CLIENT_SECRET REDDIT_USER_AGENT='$REDDIT_USER_AGENT' nohup python3.6 -u Nano/main.py &
